name: "\U0001F4A1 Feature Request"
description: Suggest an idea for this project
title: "\U0001F4A1 [FEATURE REQUEST] ..."
labels: ["enhancement", "feature"]
body:
    - type: textarea
      id: feature-description
      attributes:
        label: Feature Description
        description: Provide a clear and concise description of the new feature you are proposing.
      validations:
        required: true
  
    - type: textarea
      id: feature-solution
      attributes:
        label: Implementation Proposal
        description: Explain how you envision the feature being implemented or integrated into the project.

    - type: textarea
      id: feature-benefits
      attributes:
        label: User Benefits
        description: Describe the benefits that this feature would bring to users or stakeholders.

    - type: textarea
      id: feature-alternatives
      attributes:
        label: Alternatives Considered
        description: If you've thought about alternative approaches or workarounds, please mention them here.

    
